using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;

namespace SqlBuildManager.Console.Aci.Arm
{
     public class CurrentState
    {
        [JsonPropertyName("state")]
        public string State { get; set; }

        [JsonPropertyName("startTime")]
        public DateTime StartTime { get; set; }

        [JsonPropertyName("detailStatus")]
        public string DetailStatus { get; set; }
    }

    public class Event
    {
        [JsonPropertyName("count")]
        public int Count { get; set; }

        [JsonPropertyName("firstTimestamp")]
        public DateTime FirstTimestamp { get; set; }

        [JsonPropertyName("lastTimestamp")]
        public DateTime LastTimestamp { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("message")]
        public string Message { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }
    }

    public class InstanceView
    {
        [JsonPropertyName("restartCount")]
        public int RestartCount { get; set; }

        [JsonPropertyName("currentState")]
        public CurrentState CurrentState { get; set; }

        [JsonPropertyName("events")]
        public List<Event> Events { get; set; }

        [JsonPropertyName("state")]
        public string State { get; set; }
    }

    public class Requests
    {
        [JsonPropertyName("memoryInGB")]
        public double MemoryInGB { get; set; }

        [JsonPropertyName("cpu")]
        public int Cpu { get; set; }
    }

    public class Resources
    {
        [JsonPropertyName("requests")]
        public Requests Requests { get; set; }
    }

    public class Properties
    {
        [JsonPropertyName("image")]
        public string Image { get; set; }

        [JsonPropertyName("environmentVariables")]
        public List<object> EnvironmentVariables { get; set; }

        [JsonPropertyName("instanceView")]
        public InstanceView InstanceView { get; set; }

        [JsonPropertyName("resources")]
        public Resources Resources { get; set; }

        [JsonPropertyName("sku")]
        public string Sku { get; set; }

        [JsonPropertyName("provisioningState")]
        public string ProvisioningState { get; set; }

        [JsonPropertyName("containers")]
        public List<Container> Containers { get; set; }

        [JsonPropertyName("restartPolicy")]
        public string RestartPolicy { get; set; }

        [JsonPropertyName("ipAddress")]
        public IpAddress IpAddress { get; set; }

        [JsonPropertyName("osType")]
        public string OsType { get; set; }
    }

    public class Container
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("properties")]
        public Properties Properties { get; set; }

    }

    public class IpAddress
    {
        [JsonPropertyName("ip")]
        public string Ip { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("autoGeneratedDomainNameLabelScope")]
        public string AutoGeneratedDomainNameLabelScope { get; set; }
    }

    public class Tags
    {
    }

    public class Deployment
    {
        [JsonPropertyName("properties")]
        public Properties Properties { get; set; }

        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("location")]
        public string Location { get; set; }

        [JsonPropertyName("tags")]
        public Tags Tags { get; set; }
    }




}


