IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TransactionTest' AND TABLE_SCHEMA = 'dbo')
BEGIN
	IF EXISTS (SELECT 1 FROM dbo.TransactionTest WHERE DateTimeStamp < '{0}')
	BEGIN
		DELETE FROM TransactionTest
	END
END