//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlBuildManager.Console.Dependent.PostgreSQL.UnitTest.Properties {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlBuildManager.Console.Dependent.PostgreSQL.UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] dbconfig {
            get {
                object obj = ResourceManager.GetObject("dbconfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] dbconfig_4 {
            get {
                object obj = ResourceManager.GetObject("dbconfig_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] dbconfig_8 {
            get {
                object obj = ResourceManager.GetObject("dbconfig_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] dbconfig_doubledb {
            get {
                object obj = ResourceManager.GetObject("dbconfig_doubledb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PG_SimpleSelect {
            get {
                object obj = ResourceManager.GetObject("PG_SimpleSelect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PG_SimpleSelect_client {
            get {
                object obj = ResourceManager.GetObject("PG_SimpleSelect_client", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PG_SimpleSelect_DoubleClient {
            get {
                object obj = ResourceManager.GetObject("PG_SimpleSelect_DoubleClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PG_InsertForThreadedTest {
            get {
                object obj = ResourceManager.GetObject("PG_InsertForThreadedTest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] PG_SyntaxError {
            get {
                object obj = ResourceManager.GetObject("PG_SyntaxError", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
