apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlbuildmanager
  labels:
    app: sqlbuildmanager
spec:
  selector:
    matchLabels:
      app: sqlbuildmanager
  replicas: 2
  template:
    metadata:
      labels:
        app: sqlbuildmanager
    spec:
      containers:
      - name: sqlbuildmanager
        image: blueskydevus/sqlbuildmanager:v0.12
        resources: 
          limits:
            memory: "512M"
            cpu: "500m"
        args:
          - sbm
          - container
          - worker
        volumeMounts :
          - name: sbm
            mountPath: "/etc/sbm"
            readOnly: true
          - name: runtime
            mountPath: "/etc/runtime"
            readOnly: true
      volumes:
      - name: sbm
        secret:
          secretName: connection-secrets
      - name: runtime
        configMap:
          name: runtime-properties
      
