apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlbuildmanager
  labels:
    app: sqlbuildmanager
spec:
  selector:
    matchLabels:
      app: sqlbuildmanager
  replicas: 2
  template:
    metadata:
      labels:
        app: sqlbuildmanager
    spec:
      containers:
      - name: sqlbuildmanager
        image: blueskydevus/sqlbuildmanager:latest
        resources: 
          limits:
            memory: "512M"
            cpu: "500m"
        args:
          - sbm
          - k8s
          - worker
        volumeMounts :
          - name: sbm
            mountPath: "/etc/sbm"
            readOnly: true
          - name: runtime
            mountPath: "/etc/runtime"
            readOnly: true
      volumes:
      - name: runtime
        configMap:
          name: runtime-properties
      - name: sbm
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kvname
      
