apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'                                                 
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: '{{userAssignedClientId}}'
    keyvaultName: '{{keyVaultName}}'
    objects:  |
      array:
        - |
          objectName: StorageAccountKey
          objectType: secret 
        - |
          objectName: StorageAccountName
          objectType: secret 
        - |
          objectName: EventHubConnectionString
          objectType: secret  
        - |
          objectName: ServiceBusTopicConnectionString
          objectType: secret
        - |
          objectName: UserName
          objectType: secret
        - |
          objectName: Password
          objectType: secret      

    tenantId: '{{tenantId}}'  