//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SqlBuildManager.Enterprise.CodeReview
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SqlCodeReviewEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SqlCodeReviewEntities object using the connection string found in the 'SqlCodeReviewEntities' section of the application configuration file.
        /// </summary>
        public SqlCodeReviewEntities() : base("name=SqlCodeReviewEntities", "SqlCodeReviewEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SqlCodeReviewEntities object.
        /// </summary>
        public SqlCodeReviewEntities(string connectionString) : base(connectionString, "SqlCodeReviewEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SqlCodeReviewEntities object.
        /// </summary>
        public SqlCodeReviewEntities(EntityConnection connection) : base(connection, "SqlCodeReviewEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CodeReview> CodeReviews
        {
            get
            {
                if ((_CodeReviews == null))
                {
                    _CodeReviews = base.CreateObjectSet<CodeReview>("CodeReviews");
                }
                return _CodeReviews;
            }
        }
        private ObjectSet<CodeReview> _CodeReviews;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CodeReviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCodeReviews(CodeReview codeReview)
        {
            base.AddObject("CodeReviews", codeReview);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SqlCodeReviewModel", Name="CodeReview")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CodeReview : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CodeReview object.
        /// </summary>
        /// <param name="codeReviewId">Initial value of the CodeReviewId property.</param>
        /// <param name="reviewStatus">Initial value of the ReviewStatus property.</param>
        public static CodeReview CreateCodeReview(global::System.Guid codeReviewId, global::System.Int32 reviewStatus)
        {
            CodeReview codeReview = new CodeReview();
            codeReview.CodeReviewId = codeReviewId;
            codeReview.ReviewStatus = reviewStatus;
            return codeReview;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CodeReviewId
        {
            get
            {
                return _CodeReviewId;
            }
            set
            {
                if (_CodeReviewId != value)
                {
                    OnCodeReviewIdChanging(value);
                    ReportPropertyChanging("CodeReviewId");
                    _CodeReviewId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodeReviewId");
                    OnCodeReviewIdChanged();
                }
            }
        }
        private global::System.Guid _CodeReviewId;
        partial void OnCodeReviewIdChanging(global::System.Guid value);
        partial void OnCodeReviewIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ScriptId
        {
            get
            {
                return _ScriptId;
            }
            set
            {
                OnScriptIdChanging(value);
                ReportPropertyChanging("ScriptId");
                _ScriptId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ScriptId");
                OnScriptIdChanged();
            }
        }
        private global::System.String _ScriptId;
        partial void OnScriptIdChanging(global::System.String value);
        partial void OnScriptIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReviewDate
        {
            get
            {
                return _ReviewDate;
            }
            set
            {
                OnReviewDateChanging(value);
                ReportPropertyChanging("ReviewDate");
                _ReviewDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReviewDate");
                OnReviewDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReviewDate;
        partial void OnReviewDateChanging(Nullable<global::System.DateTime> value);
        partial void OnReviewDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReviewBy
        {
            get
            {
                return _ReviewBy;
            }
            set
            {
                OnReviewByChanging(value);
                ReportPropertyChanging("ReviewBy");
                _ReviewBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReviewBy");
                OnReviewByChanged();
            }
        }
        private global::System.String _ReviewBy;
        partial void OnReviewByChanging(global::System.String value);
        partial void OnReviewByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReviewStatus
        {
            get
            {
                return _ReviewStatus;
            }
            set
            {
                OnReviewStatusChanging(value);
                ReportPropertyChanging("ReviewStatus");
                _ReviewStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReviewStatus");
                OnReviewStatusChanged();
            }
        }
        private global::System.Int32 _ReviewStatus;
        partial void OnReviewStatusChanging(global::System.Int32 value);
        partial void OnReviewStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReviewNumber
        {
            get
            {
                return _ReviewNumber;
            }
            set
            {
                OnReviewNumberChanging(value);
                ReportPropertyChanging("ReviewNumber");
                _ReviewNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReviewNumber");
                OnReviewNumberChanged();
            }
        }
        private global::System.String _ReviewNumber;
        partial void OnReviewNumberChanging(global::System.String value);
        partial void OnReviewNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CheckSum
        {
            get
            {
                return _CheckSum;
            }
            set
            {
                OnCheckSumChanging(value);
                ReportPropertyChanging("CheckSum");
                _CheckSum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CheckSum");
                OnCheckSumChanged();
            }
        }
        private global::System.String _CheckSum;
        partial void OnCheckSumChanging(global::System.String value);
        partial void OnCheckSumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidationKey
        {
            get
            {
                return _ValidationKey;
            }
            set
            {
                OnValidationKeyChanging(value);
                ReportPropertyChanging("ValidationKey");
                _ValidationKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidationKey");
                OnValidationKeyChanged();
            }
        }
        private global::System.String _ValidationKey;
        partial void OnValidationKeyChanging(global::System.String value);
        partial void OnValidationKeyChanged();

        #endregion
    
    }

    #endregion
    
}
