//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SqlSync.Connection {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.mckechney.com/SqlBuildManager/2010/05/RegisteredServers.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.mckechney.com/SqlBuildManager/2010/05/RegisteredServers.xsd", IsNullable=false)]
    public partial class RegisteredServers {
        
        private ServerGroup[] serverGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServerGroup")]
        public ServerGroup[] ServerGroup {
            get {
                return this.serverGroupField;
            }
            set {
                this.serverGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.mckechney.com/SqlBuildManager/2010/05/RegisteredServers.xsd")]
    public partial class ServerGroup {
        
        private RegServer[] regServerField;
        
        private string nameField;
        
        public ServerGroup() {
            this.nameField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegServer")]
        public RegServer[] RegServer {
            get {
                return this.regServerField;
            }
            set {
                this.regServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.mckechney.com/SqlBuildManager/2010/05/RegisteredServers.xsd")]
    public partial class RegServer {
        
        private string nameField;
        
        public RegServer() {
            this.nameField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
