USE [master]
GO

CREATE DATABASE [SqlCodeReview]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SqlCodeRreview', FILENAME = N'M:\TLO\TLO_MSTR\SQLData1\MSSQL11.TLO_MSTR\MSSQL\DATA\SqlCodeRreview.mdf' , SIZE = 5072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SqlCodeRreview_log', FILENAME = N'M:\TLO\TLO_MSTR\SQLData1\MSSQL11.TLO_MSTR\MSSQL\DATA\SqlCodeRreview_log.ldf' , SIZE = 4096KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SqlCodeReview] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SqlCodeReview].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SqlCodeReview] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SqlCodeReview] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SqlCodeReview] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SqlCodeReview] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SqlCodeReview] SET ARITHABORT OFF 
GO

ALTER DATABASE [SqlCodeReview] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SqlCodeReview] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SqlCodeReview] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SqlCodeReview] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SqlCodeReview] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SqlCodeReview] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SqlCodeReview] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SqlCodeReview] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SqlCodeReview] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SqlCodeReview] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SqlCodeReview] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SqlCodeReview] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SqlCodeReview] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SqlCodeReview] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SqlCodeReview] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SqlCodeReview] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SqlCodeReview] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SqlCodeReview] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SqlCodeReview] SET RECOVERY FULL 
GO

ALTER DATABASE [SqlCodeReview] SET  MULTI_USER 
GO

ALTER DATABASE [SqlCodeReview] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SqlCodeReview] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SqlCodeReview] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SqlCodeReview] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SqlCodeReview] SET  READ_WRITE 
GO


