
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: runtime-properties
data:
  DacpacName: ''
  PackageName: 'SimpleSelect.sbm'
  JobName: 'build14'
  Concurrency: '5'
  ConcurrencyType: 'MaxPerServer'