name: .NET Core Build

on:
  push:
    branches: 
      - master
      - dotnetstandard
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Set build config variable
      run: "::set-env name=BUILD_CONFIG::Release"        

    - name: Restore dependencies
      run: dotnet restore ./src/sqlsync.sln

    - name: Build Main Solution
      run: dotnet build ./src/sqlsync.sln --configuration $BUILD_CONFIG --no-restore

    - name: Run SqlBuildManager.Console.UnitTest
      run: dotnet test ./src/SqlBuildManager.Console.UnitTest/SqlBuildManager.Console.UnitTest.csproj --configuration $BUILD_CONFIG

    - name: Run SqlBuildManager.Enterprise.UnitTest
      run: dotnet test ./src/SqlBuildManager.Enterprise.UnitTest/SqlBuildManager.Enterprise.UnitTest.csproj --configuration $BUILD_CONFIG

    - name: Run SqlBuildManager.ScriptHandling.UnitTest
      run: dotnet test ./src/SqlBuildManager.ScriptHandling.UnitTest/SqlBuildManager.ScriptHandling.UnitTest.csproj --configuration $BUILD_CONFIG

    - name: Run SqlSync.Connection.UnitTest
      run: dotnet test ./src/SqlSync.Connection.UnitTest/SqlSync.Connection.UnitTest.csproj --configuration $BUILD_CONFIG

    - name: Run SqlSync.ObjectScript.UnitTest
      run: dotnet test ./src/SqlSync.ObjectScript.UnitTest/SqlSync.ObjectScript.UnitTest.csproj --configuration $BUILD_CONFIG

    - name: Run SqlSync.SqlBuild.UnitTest
      run: dotnet test ./src/SqlSync.SqlBuild.UnitTest/SqlSync.SqlBuild.UnitTest.csproj --configuration $BUILD_CONFIG

    - name: Publish the Windows desktop app
      run: dotnet publish ./src/SqlSync/SqlSync.csproj -r win-x64 --configuration $BUILD_CONFIG

    - name: Publish the legacy Console CLI desktop app
      run: dotnet publish ./src/SqlBuildManager.Console/SqlBuildManager.Console.csproj -r win-x64 --configuration $BUILD_CONFIG

    - name: Publish the new Console CLI desktop app
      run: dotnet publish ./src/SqlBuildManager.Console/sbm.csproj -r win-x64 --configuration $BUILD_CONFIG

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SqlBuildManager CLI
        path: "./src/SqlBuildManager.Console/bin/$BUILD_CONFIG/netcoreapp3.1/win-x64/publish"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SqlBuildManager Desktop
        path: "./src/SqlSync/bin/$BUILD_CONFIG/netcoreapp3.1/win-x64/publish"        


    