name: .NET Core Build

on:
  push:
    branches: 
      - master
      - dotnetstandard
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Restore dependencies
      run: dotnet restore ./src/sqlsync.sln

    - name: Build Main Solution
      run: dotnet build ./src/sqlsync.sln --configuration Release --no-restore

    - name: Publish the Windows desktop app
      run: dotnet publish ./src/SqlSync/SqlSync.csproj -r win-x64 --configuration Release

    - name: Publish the Console CLI desktop app
      run: dotnet publish ./src/SqlBuildManager.Console/sbm.csproj -r win-x64 --configuration Release

    # - name: Test
    #   run: dotnet test --no-restore --verbosity normal

    # - name: Install 7Zip PowerShell Module
    #   shell: powershell
    #   run: Install-Module 7Zip4PowerShell -Force -Verbose

    # - name: Create CLI Zip
    #   shell: powershell
    #   run: powershell Compress-7Zip "./src/SqlBuildManager.Console/bin/Release/netcoreapp3.1/win-x64/publish" -ArchiveFileName "sbm.zip" -Format Zip

    # - name: Create Desktop 7Zip
    #   shell: powershell
    #   run: powershell Compress-7Zip "./src/SqlSync/bin/Release/netcoreapp3.1/win-x64/publish" -ArchiveFileName "sqlbuildmanager.zip" -Format Zip


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SBM Command Line Interface
        path: ""./src/SqlBuildManager.Console/bin/Release/netcoreapp3.1/win-x64/publish""

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SqlBuildManager Desktop
        path: "./src/SqlSync/bin/Release/netcoreapp3.1/win-x64/publish"        


    